### ISSUE TITLE
Attach Debugger

### ISSUE THREAD

**Issue by toeb** [toeb/CTestTestAdapter#4]
Currently when you start a test in Debug mode the debugger will attach itself only to the cmake executable.  CMake in turn however executes a command when a test defined by `add_test` is called.  The cmake process would have to be inspected and then the debugger would need to be attached to any child process (or correct child process) when spawned

**Comment by micst** [comment]
This is now also addressed by the micst-branch:

https://github.com/micst/CTestTestAdapter

I will do the merge-work as soon as I find time for it (but it can be weeks or months).
