### ISSUE TITLE
Better Test Discovery 

### ISSUE THREAD

**Issue by toeb** [toeb/CTestTestAdapter#5]
Currently Test Discovery is does not cache the tests it discovers.  This is slow and also the TestExplorer does not exactly know how to handle this an thus grays out all tests when a single test is run.  This should be corrected

**Comment by micst** [comment]
In my fork I added some file listener mechanisms to avoid re-scanning with `ctest -N` over and over again. There are some additional changes as well like extracting the filepath of the ctest executable from the `CMakeCache.txt` and listening to cache changes...

This all adds up to quite a lot of changes. I'm not sure if they are really able to merge, but maybe some mechanisms could be adapted.

**Comment by toeb** [comment]
Hi thanks a lot for that. :D I'm currently trying to get it to run with vs2015 and will create a new package
