### ISSUE TITLE
Support for Visual Studio 2015

### ISSUE THREAD

**Issue by micst** [toeb/CTestTestAdapter#7]
Did anyone have success in using the test adapter for **Visual Studio 2015**? I am not able to get the `ITestContainerDiscoverer` running even though it is working fine in VS 2013.

I opened topics at stackoverflow  and social.msdn.microsoft.com for that:

http://stackoverflow.com/questions/34679388/itestcontainerdiscoverer-not-working-in-visual-studio-2015

https://social.msdn.microsoft.com/Forums/en-US/a41946a1-9560-4929-8132-5404c381ad95/itestcontainerdiscoverer-not-working-in-visual-studio-2015?forum=vsunittest

**Comment by toeb** [comment]
Hi, I'll try to create a vs2015 package as soon as I merge #6 .

**Comment by micst** [comment]
I got it working. Will commit the changes to my fork today (hopefully).

**Comment by Artfunkel** [comment]
I'd like to reopen this bug because the changes were never integrated. The pre-built extension by @micst is broken for VS2015 too.

Here's a working 2015 build: [CTestTestAdapter.zip](https://github.com/toeb/CTestTestAdapter/files/300822/CTestTestAdapter.zip)

**Comment by Artfunkel** [comment]
Huh, OK. I didn't make any code changes, I just opened the solution in VS2015, fixed some references that were missing on my system, and built.

I don't know much about Visual Studio extensions but could it simply be that you can't target 2013 and 2015 with the same binary?

**Comment by micst** [comment]
Sorry, I thought you changed something in the code because of the "working build" compared to the not working.

I'm not perfectly sure about support for multiple VS versions in one package either but I really believe it's possible. There's a bunch of VSIX extensions out there which support this.

The adapter works on my machine, but I have 4 VS versions installed beside each other. Probably not a good test environment...

**Comment by micst** [comment]
Ok, after changing the whole build process to CMake, there are now three separate VSIX packages built, one for every VS version (2012, 2013, 2015). The 2012 version seems to freeze the IDE sometimes though ... :-(. You have to get them from my fork at the moment: https://github.com/micst/CTestTestAdapter/tree/master/dist

PS: small drawback of the new build system: it **requires native C# support for CMake**, which is not yet in upstream but only available in my fork (https://github.com/micst/CMake). This is why I didn't create a pull request yet.
